name: Update gh-pages

on:
  push:
    branches: [ main ]

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check gh-pages Exists
        id: check-gh-pages
        shell: bash
        run: |
          GITHUB_URL="https://github.com/${{ github.repository }}"
          if git ls-remote --exit-code --heads $GITHUB_URL gh-pages; then
            echo "::set-output name=found::true"
            echo "gh-pages branch found. Updating..."
          else
            echo "::set-output name=found::false"
            echo "gh-pages branch not found. Skipping..."
          fi
      - uses: actions/checkout@v2
        if: steps.check-gh-pages.outputs.found == 'true'
      - name: Build
        if: steps.check-gh-pages.outputs.found == 'true'
        run: |
          npm install
          npm run build
      - name: git setup
        if: steps.check-gh-pages.outputs.found == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: git commit and push
        if: steps.check-gh-pages.outputs.found == 'true'
        run: |
          git checkout -B gh-pages
          git add dist --force
          git push origin gh-pages --force
