name: Update gh-pages

on:
  push:
    branches: [ main ]

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub Repository Variables
        id: setup-vars
        uses: actions/github-script@v2
        with:
          # Creates output variables to be used in later steps since there is
          # no native way to split the strings within the script itself
          script: |
            core.setOutput('owner', "${{ github.repository }}".split('/')[0])
            core.setOutput('repo', "${{ github.repository }}".split('/')[1])
      - name: Check gh-pages Exists
        id: check-gh-pages
        shell: bash
        run: |
          GITHUB_URL="https://github.com/${{ github.repository }}"
          if git ls-remote --exit-code --heads $GITHUB_URL gh-pages; then
            echo "::set-output name=found::true"
            echo "gh-pages branch found. Updating..."
          else
            echo "::set-output name=found::false"
            echo "gh-pages branch not found. Skipping..."
          fi
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
      - run: |
          git fetch --no-tags --depth=1 origin gh-pages
      - name: magic
        run: git add dist --force
      - name: git setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: magic 2
        run: git commit -m "gh-pages build"
      - name: Update gh-pages
        if: steps.check-gh-pages.outputs.found == 'true'
        run: |
          git push origin gh-pages --force
  # build-gh-pages:
  #   runs-on: ubuntu-latest
  #   needs: update-gh-pages
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         token: ${{ secrets.USER_TOKEN }} # TODO: Make sure this gets changed!!!!!!
  #         ref: gh-pages
  #       run: npm run build
  #     - name: git setup
  #       run: |
  #         git config user.name github-actions
  #         git config user.email github-actions@github.com
  #     - name: magic 2
  #       run: git commit -m "gh-pages build"
  #     - name: magic 3
  #       run: git push
